#!/bin/bash

source ~/.rbenv/libexec/_profile

if [[ "$#" = 0 ]]; then
  set -- ree 1.9.3
fi

for rb in "$@"; do
  echo "> testing $rb"
  pth_a="$(mktemp -t XXXXXX)"
  pth_b="$(mktemp -t XXXXXX)"

  pushd $rb > /dev/null
  rm -rf vendor/bundle
  bundle --quiet --local --path vendor/bundle
  ./run > $pth_b
  popd > /dev/null

  ./run.sh $rb > $pth_a

  if diff $pth_a $pth_b; then
    cat $pth_a
  fi
  rm -f $pth_a $pth_b
done
