#!/bin/bash

nm_ruby="$1"; shift
ver_bundler="$1"; shift

shome=$(pwd)
PATH="$shome/sbin:$PATH"
PATH="$PATH:$shome/.rvm/bin"

rvm install "$nm_ruby" --disable-binary --skip-gemsets --verify-downloads 2 "$@"
rvm prepare "$nm_ruby" --install
rvm uninstall "$nm_ruby"
