#!/bin/bash

nm_ruby="$1"; shift
ver_bundler="$1"; shift

YARVM=$(pwd)
PATH="$YARVM/sbin:$PATH"
PATH="$PATH:$YARVM/.rvm/bin"

export rvm_path="$shome/.rvm"

set +f; rvm mount --skip-gemsets -r ./*${nm_ruby}*.tar.*; set -f

source $YARVM/.rbenv/libexec/_rbenv
cd test/1.9.3
gem install bundler -c "$ver_bundler"
rbenv rehash
hash -r
./run
