#!/bin/bash

nm_ruby="$1"; shift
ver_bundler="$1"; shift

shome=$(pwd)
PATH="$shome/sbin:$PATH"
PATH="$PATH:$shome/.rvm/bin"

export rvm_path="$shome/.rvm"

set +f; rvm mount --skip-gemsets -r ./*${nm_ruby}*.tar.*; set -f
rvm-exec "$nm_ruby" gem list --local
rvm-exec "$nm_ruby@global" gem install bundler -v "$ver_bundler"
