#!/bin/bash

nm_ruby="$1"; shift
ver_bundler="$1"; shift

YARVM=$(pwd)
PATH="$YARVM/sbin:$PATH"
PATH="$PATH:$YARVM/.rvm/bin"

bin_prefix="$(bin/guess-os)$(echo ${YARVM} | tr / _)"
mv -v "$VAULT/packages/${bin_prefix}/*" .

export rvm_path="$YARVM/.rvm"

set +f; rvm mount --skip-gemsets -r ./*${nm_ruby}*.tar.*; set -f

(set +f; ln -nfs $YARVM/.rvm/rubies/*${nm_ruby}* $YARVM/.rbenv/versions/)
for a in $(set +f; ls -d $YARVM/.rvm/rubies/*${nm_ruby}*); do
  fn_ruby="$(basename $nm_ruby)"
  case $fn_ruby in
    ruby-*)
      ln -nfs $a $YARVM/.rbenv/versions/$(echo $fn_ruby | cut -d- -f2)
      ;;
    *)
      ln -nfs $a $YARVM/.rbenv/versions/$(echo $fn_ruby | cut -d- -f1-2)
      ln -nfs $a $YARVM/.rbenv/versions/$(echo $fn_ruby | cut -d- -f1)
      ;;
  esac
done

source $YARVM/.rbenv/libexec/_rbenv

cd test/$nm_ruby
gem install bundler -v "$ver_bundler"
rbenv rehash
hash -r
cd ..
./run $nm_ruby
